### PR TITLE
Code of conduct

### PR DESCRIPTION
**Pull request by sibirrer**
This is a code of conduct taken from https://www.contributor-covenant.org/version/1/4/code-of-conduct.html
and modified with the email address of the developers. This is a rather generic code of conduct.

To apply for NumFocus affiliation (and potential sponsorship down the road), a CoC is required.
Any feedback is more than welcomed!

### CODE REVIEW

**Comment by ajshajib** [comment]
The CoC looks great to me. But, the PR also includes some code updates, which may not have been intended to be part of this PR?

**Comment by sibirrer** [comment]
> The CoC looks great to me. But, the PR also includes some code updates, which may not have been intended to be part of this PR?

ah yes, was playing around with deprecation warnings in numba but could not resolve them. I make another minor PR and then update this one such that hopefully only the CoC is here

**Review by ajshajib — APPROVED** [review]

**Comment by sibirrer** [comment]
@dangilman do you have any comments on the CoC?

**Review by dangilman — APPROVED** [review]

**Comment by dangilman** [comment]
> @dangilman do you have any comments on the CoC?

looks fine to me

**Pull request merged**
