### PR TITLE
Add support for CONVERGENCE lens model in COOLEST interface

### PR DESCRIPTION
**Pull request by aymgal**
Addresses issue #589 .

I anticipate that the overall test coverage will decrease, because the relevant unit test routines have not been updated. If this is the case, it will take me some more time to ensure proper code coverage, since I need to update the coolest files used in the unit test routines, but I don't have the original code for that. I am contact with Lyne to hopefully get her code. 

The lenstronomy COOLEST interface can in theory still be used though, from the branch `pr-coolest-updt`.

### CODE REVIEW

**Comment by sibirrer** [comment]
Thank you @aymgal ! I think you can also just edit the current COOLEST files in the test folder. I certainly don't want lenstronomy to require other code available to update the testing, if possible

**Comment by aymgal** [comment]
@sibirrer In theory yes, I could manually update those. But these specific files have been exported using an old interface of COOLEST, which make them quite tricky to edit by hand. Hence I would prefer to have the original script, that I can then use to generate new COOLEST files which will be human-editable in the future.

**Review by sibirrer — APPROVED** [review]
@aymgal I approve this PR for now as we would like to move forward to a better integration of COOLEST with SLSim. I hope we find a way to have smooth testing and possibly expansions of the COOLEST integration without the need of an 'expert' (aka you)

**Review by sibirrer — CHANGES_REQUESTED** [review]
@aymgal sorry to ping you again. I see that there are basically no tests for this new feature and I really don't want to have definitions and features without tests in lenstronomy to notice when things change elsewhere. I hope you can add a brief test function - thank you!

**Comment by aymgal** [comment]
Hi @sibirrer, this week is too busy for me but starting from Tuesday next week I can try to work on this. At least to improve the testing part... For the interface itself, it should probably be improved in order to ease future updates.

**Comment by aymgal** [comment]
I made it easier to update the COOLEST templates used for the tests (including a new short script to programmatically generate an empty template).
  
I plan to complete the test coverage in the next few days.

**Comment by sibirrer** [comment]
Thank you very much @aymgal, really appreciate it!

**Comment by aymgal** [comment]
@sibirrer Ok it's a bit hard for me to go further than that for testing coverage, given the overall implementation of the interface. I hope it is fine as it is!

**Pull request merged**
