### PR TITLE
Update MultiGaussianEllipseKappa to support varying ellipticities and Include in profile list base

### PR DESCRIPTION
**Pull request by RosettaGit**
This PR is a continuation of the now-closed #629 and can be considered a supplement to #630. To avoid ambiguity, @ajshajib has changed the name from GaussianEllipseKappaSet to MultiGaussianEllipseKappa in #630 and also modified the corresponding class names to distinguish between potential inputs and kappa inputs. Thanks to Anowar’s efforts, the class name ‘MULTI_GAUSSIAN_ELLIPSE_KAPPA’ added in this PR can accurately and describe the function and input of the class.”

### CODE REVIEW

**Comment by ajshajib** [comment]
Thanks a lot, @RosettaGit. Can you kindly increase test coverage to cover lines 471-475 in profile_list_base.py?

**Review by ajshajib — CHANGES_REQUESTED** [review]
Thanks a lot, @RosettaGit. Can you kindly increase test coverage to cover lines 471-475 in profile_list_base.py?

**Comment by RosettaGit** [comment]
@ajshajib lines 471-475 in profile_list_base.py has been covered. Sorry for the delay.

**Comment by ajshajib** [comment]
Thank you very much, @RosettaGit!

**Review by ajshajib — APPROVED** [review]

**Pull request merged**
