### PR TITLE
Format with black to 88 character limit

### PR DESCRIPTION
**Pull request by ajshajib**
All the codes have been auto-formatted with black for better general readability. This is an experimental PR just to check how the formatted code would look and if all tests pass. So, this PR may not be merged as of now.

Check #499 for relevant discussion.

### CODE REVIEW

**Comment by sibirrer** [comment]
Thank you @ajshajib ! Does look not too bad. Does this automatically format new PR's when merged or would we have to do it semi-manually in the future?

**Comment by ajshajib** [comment]
I can add an action that does this auto-formatting for all new PRs and add that commit to the PR on its own. It would be better to add that action as a new PR, since it is changing many files, so testing with that new action within this PR would be tedious.

**Comment by sibirrer** [comment]
> I can add an action that does this auto-formatting for all new PRs and add that commit to the PR on its own. It would be better to add that action as a new PR, since it is changing many files, so testing with that new action within this PR would be tedious.

I see, this sounds great @ajshajib! As you stated, perhaps let the community have some inputs/thoughts. Perhaps you can also post it on the Slack channel? Happy to move it forward (there are already conflicts generated form this PR with recently merged PR's...)

**Comment by ajshajib** [comment]
Sure, posted a message on Slack. I can take care of the conflicts when we finalize to proceed with merging this PR. 🙂

**Review by sibirrer — APPROVED** [review]
Thanks a lot! It looks like there are now merge conflicts. I hope you can re-run black on the updated main branch such that it does not create merge conflicts. I will held back on merging other things to main till then

**Comment by ajshajib** [comment]
> Thanks a lot! It looks like there are now merge conflicts. I hope you can re-run black on the updated main branch such that it does not create merge conflicts. I will held back on merging other things to main till then

I am working on the merge conflicts. I think the easiest think to do would be to close this PR, and run the autoformatters on the latest `main` for a new PR.

**Comment by sibirrer** [comment]
> > Thanks a lot! It looks like there are now merge conflicts. I hope you can re-run black on the updated main branch such that it does not create merge conflicts. I will held back on merging other things to main till then
> 
> I am working on the merge conflicts. I think the easiest think to do would be to close this PR, and run the autoformatters on the latest `main` for a new PR.

That makes sense. Whatever is the least hassle. I hope it will also not impact too much currently pending PR's

**Comment by ajshajib** [comment]
Closing this since #502 now covers the latest `main`.

**Pull request closed without merging**
