### PR TITLE
Update CONTRIBUTING.rst

### PR DESCRIPTION
**Pull request by ajshajib**
I made the following updates:
1. specified 120 characters as the line limit, extending the PEP8 guideline,
2. stated reStructuredText Format as the preferred style, and
3. made minor fixes to typos and punctuation.

### CODE REVIEW

**Comment by ajshajib** [comment]
@sibirrer, is 100 the correct number for the maximum line length?

**Comment by sibirrer** [comment]
> @sibirrer, is 100 the correct number for the maximum line length?

@ajshajib I used PyCharm's default 120 lines in my editor but happy to use a different one (just will trigger a lot of PEP8 issues :) )

**Comment by ajshajib** [comment]
> @ajshajib I used PyCharm's default 120 lines in my editor but happy to use a different one (just will trigger a lot of PEP8 issues :) )

Ok, I will revise it to 120. My memory was not clear on this, that's why I took a look at CONTRIBUTING, but it was not there, hence this PR. 🙂

**Comment by ajshajib** [comment]
@sibirrer, I have revised the line length limit, please check and merge if everything seems fine to you.

**Review by sibirrer — APPROVED** [review]
Looks great, thank you @ajshajib!
Let's see how many PEP8 errors there are...I bet in the thousand...

**Comment by ajshajib** [comment]
@sibirrer, the main argument for a shorter line-length limit is this. This is how it looks like if I want to have a split screen on PyCharm to look at the main file and the test file side by side while working. You can see the lines overflowing on both screens needing me to scroll sideways. The vertical grey lines right before the right-edge is showing the 88 character mark The 88-character is the default setting chosen by the `black` auto-formatter, and this number makes sense given the modern screen sizes and resolutions.  For example, this screenshot is on my MacBook Pro (screen size with 1768p horizontal resolution and 12-point font size.


Screenshot 2023-08-17 at 12 57 00 PM

**Comment by ajshajib** [comment]
@sibirrer, the main argument for a shorter line-length limit is this. This is how it looks like if I want to have a split screen on PyCharm to look at the main file and the test file side by side while working. You can see the lines overflowing on both screens needing me to scroll sideways. The vertical grey lines right before the right-edge is showing the 88 character mark The 88-character is the default setting chosen by the `black` auto-formatter, and this number makes sense given the modern screen sizes and resolutions.  For example, this screenshot is on my MacBook Pro (screen size with 1768p horizontal resolution and 12-point font size.

Screenshot 2023-08-17 at 1 00 25 PM

**Comment by ajshajib** [comment]
I will move the above point to a discussion in case people from the community would like to pitch in.

**Pull request merged**
